export const routes = {
  DEFAULT: "/",
  LOGIN: "/login",
  ANNOUNCEMENT: "/announcement",
  ANNOUNCEMENT_CREATE: "/announcement/create",
  INTRODUCTION: "/introduce",
  ANNOUNCEMENT_EDIT: "/announcement/edit/:id",
  ANNOUNCEMENT_DETAIL: "/announcement/:id",
  FACILITY: "/facility",
  CONTENT: "/content",
  CONTENT_CREATE: "/content/create",
  CONTENT_EDIT: "/content/edit/:id",
  LIVING_LAB: "/living-lab",
  LIVING_LAB_DETAIL: "/living-lab/:id",
  LIVING_LAB_CREATE: "/living-lab/create",
  LIVING_LAB_EDIT: "/living-lab/edit/:id",
  USER_MANAGEMENT: "/manager-user",
  CAMPAIGN: "/campaign",
  CAMPAIGN_DETAIL: "/campaign/:id",
  CAMPAIGN_CREATE: "/campaign/create",
  CAMPAIGN_EDIT: "/campaign/edit/:id",
  FREE_BOARD: "/freeboard",
  FREE_BOARD_DETAIL: "/freeboard/:id",
  FREE_BOARD_CREATE: "/freeboard/create",
  FREE_BOARD_CREATE_USER: "/freeboard/create_user",
  FREE_BOARD_EDIT: "/freeboard/edit/:id",
  REGISTER: "/register",
};
